name : CI

on:
  push:
    branches: [ new_branch ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      platform: AWS
      region: central
      profile_path: profile/

    steps:
      - uses: actions/checkout@v2
      
      - name: Display GH Default env vars
        run: |
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"

      - name: List all files
        run: ls

      - name: Display custom environment variables
        run: |
          echo "The platform is ${{ env.platform}}"
          echo "The region is ${{ env.region }}"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Run Python Script
        run: python create_file.py

      - name: List all the new files
        run: ls