name : CI

on:
  push:
    branches: [ new_branch ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      platform: AWS
      region: central
      profile_path: profile/
    
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.tagname }}
      output3: ${{ steps.contents.outputs.data }}

    steps:
      - uses: actions/checkout@v2
      
      - id: step1
        run: echo "::set-output name=test::hello"

      - id: step2
        run: |
          tagvar = world
          echo "::set-output name=tagname::$tagvar"

      - name: Display GH Default env vars
        run: |
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"

      - name: List all files
        run: ls

      - name: Display custom environment variables
        run: |
          echo "The platform is ${{ env.platform}}"
          echo "The region is ${{ env.region }}"

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Run Python Script
        run: |
          python create_file.py
          contents= $( cat read_me.txt)
          echo "::set-output name=data::$contents"

      - name: List all the new files
        run: ls

  display:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
      - name: Print a value
        run: echo Hello from another job
      
      - name: Print Output from previous job
        run:  echo ${{ needs.build.outputs.output1 }} ${{ needs.build.outputs.output2 }} ${{ needs.build.outputs.output3 }}
